### ISSUE TITLE
export direct to adegenet genind object

### ISSUE THREAD

**Issue by plantarum** [lvclark/polysat#3]
Hi,

I have a dataset with a mix of diploids and triploids. I think polysat is the best/only way to deal with both cytotypes together, but I would like to analyze the diploids with adegenet and related tools. Is there a way to export directly from genambig to genind/genpop?

The best I've managed so far is to select the diploid subset of my genambig, export that to a STRUCTURE file, then read that back in with the adegenet import functions. That seems a bit round-about, have a missed a more direct approach?

Best,

Tyler

**Comment by lvclark** [comment]
Yes.  See the `gendata.to.genind` function.

**Comment by plantarum** [comment]
Hi Lindsay,

I ran into this again today. I'm sure I remember discussing this with you over email, but I can't find anything in my archives.

Is it possible to retain locus info when exporting from gendata to genind?

Thanks

**Comment by lvclark** [comment]
Which locus info in particular?  I think because it is coded as presence/absence, there is no `@loc.fac` slot, although you could do `sub("-[[:digit:]]*$", "", colnames(x@tab))` to get a vector of locus IDs for each allele.

**Comment by plantarum** [comment]
Exporting a genambig object to STRUCTURE format, then reading that into genind, I get:

```
> diploidGI
/// GENIND OBJECT /////////

 // 171 individuals; 8 loci; 59 alleles; size: 72.2 Kb
...
```

The same object converted via `gendata.to.genind` is:

```
> dipDirect
/// GENIND OBJECT /////////

 // 171 individuals; 59 loci; 59 alleles; size: 59.9 Kb
```

Each allele is treated as a separate locus. That makes it impossible to calculate stats based on loci (`adegenet::basic.stats`).

I tried pulling the loci names out of the column names, similar to what you've suggested. But adegenet doesn't let you assign loci with `locFac`, they need to be defined when you create the genind object I think.

**Comment by plantarum** [comment]
Should have included the original object:

```
summary(diploids)
Dataset with allele copy number ambiguity.
Dataset for Celtis SSRs
Number of missing genotypes: 36
171 samples, 8 loci.
3 populations.
Ploidies: 2
Length(s) of microsatellite repeats: 3 6
```

**Comment by lvclark** [comment]
Yes, that's a difference between the "codom" and "PA" format.  polysat exports to "PA" format because I don't think "codom" allows allele copy number ambiguity.

**Comment by plantarum** [comment]
That makes sense. In my case, working with mixed ploidy, my diploids are 'guilty by association' with the triploids. I actually know their allele dosage, but since they were imported along with a bunch of triploids they've ended up in a data structure where we assume dosage is never completely known.

I could put together some code to deal with this edge case (i.e., exporting diploids with complete allele dosage from genambig to genind) if it would be helpful. Or perhaps it's too unlikely that other people will run into this with polysat, given it explicitly targets polyploids?

**Comment by lvclark** [comment]
Yeah, it doesn't make sense to me to add any "diploids only" functionality to polysat, but thanks for the offer!
